### ISSUE TITLE
Aktif kayıtlı öğrencinin ders(ler)ini almasını sağla

### ISSUE THREAD

**Issue by baran** [omu/nokul#1009]
#### İş kaydı
Aktif kayıtlı öğrencinin geçerli dönemde (akademik takvimden "ders kayıt" döneminde olduğu bilgisi kontrol edildikten sonra, öğrencinin durumuna göre ders seçimi yaptırılarak **kayıtlanması** işlemi gerçekleştirilecek.

[//]: # (Kısa ve net şekilde iş kaydının hedeflediği problemi tanımla)
- omu/po#14

[//]: # (Kısa ve net bir şekilde çözüm önerini yaz)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [ ] İş kaydı hata bildirimi veya ürün özelliği dışında bir niteliğe sahip
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
- [use-cases](https://github.com/omu/po/blob/master/projects/nokul/use-cases/uc-0023-ogrencinin-ders-secmesi.md)
- [ders kayıt mockup](http://po.omu.sh/nokul/mockups/student/)

[//]: # (Örnek çözümler)
