### ISSUE TITLE
Öğretim elemanının not girişi yapmasını sağla

### ISSUE THREAD

**Issue by ekural** [omu/nokul#1430]
#### Kullanım senaryosu
Öğretim elemanları kendilerine atanmış dersler için not girişi yapabilmeli. Ders koordinatörleri tüm öğrenciler için, alt grup öğretim elemanları ise kendi grupları için not girişi yapabilmeli.

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [x] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik
[Mockup](http://po.omu.sh/nokul/mockups/lecturer/)
