### ISSUE TITLE
GSuite entegrasyonunu gerçekle

### ISSUE THREAD

**Issue by abdagli** [omu/nokul#655]
**Açıklama:**
Kullanıcıları ve mail'leri zimbradan gsuite'e aktar ve zimbra'ya depend eden servislerin hepsini gsuite ile çalışabilir hale getir.

**Kontrol listesi**

* [x] İş kaydınızın başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi vb.) uygun mu?
* [x] Use case, product ekibi tarafından incelenip onaylandı mı?
* [ ] Use case ve oluşturulan mockup'lar müşteri tarafından onaylandı mı?

**Ek içerik:**

[//]: # (Kaynaklar, dış bağlantılar, ekran görüntüleri, örnek çözümler ve benzeri diğer kaynakları ekleyiniz.)

**Comment by roktas** [comment]
Bu iş kaydını epic + invalid yapıyorum, bk milestone'lar.  Triage'den sonra kapatalım.
