### ISSUE TITLE
Milestone esaslı roadmap oluşturulmalı

### ISSUE THREAD

**Issue by roktas** [omu/nokul#919]
Merkez depoda milestone (durak) esaslı bir iş akışını dokümante ettim.  Taslak dokümanlara https://doc.omu.sh/ adresinden (iş akışları-github) erişebilirsiniz.  Gün içinde etiketleri değiştireceğim.  @omu/product: bu tamamlandığında sizden istediğim:

- [ ] Aşağıdaki milestone'lara son halini verelim
- [ ] Milestone'ları sıralayalım
- [ ] Milestone'ları belirlenen sırayla girelim
- [ ] Tüm iş kayıtlarını yeni etiket ve proje sistemine göre elden geçirelim
- [ ] İş kayıtlarını mümkün olduğunca (hepsi olmayabilir) milestone'lara bağlayalım
- [ ] İlk milestone'a yoğunlaşarak gerekirse yeni iş kayıtları oluşturalım
- [ ] İlk veya ilk bir kaç milestone'a due date koyalım

Milestone taslak
---------------------

### Uygulama

Depo: https://github.com/omu/nokul

- Kullanıcı rolleri etkin
- Personel izin talepleri yönetilebiliyor
- Personel görevlendirmeleri yönetilebiliyor
- Mekanlar G-Suite ile entegre yönetilebiliyor
- Yeni personel kaydı yapılabiliyor
- Öğrenci kayıtlanabileceği dersleri görebiliyor
- Öğrenci ders kaydını gerçekleştirebiliyor
- Öğretici not girebiliyor
- Öğrenci notlarını görüntüleyebiliyor
- Ders değerlendirmeleri yapılabiliyor
- Müfredat değişiklikleri yönetilebiliyor
- Yeni öğrenci kaydı yapılabiliyor
- Mezun öğrenci belirlemesi yapılabiliyor
- Diploma işlemleri yapılabiliyor
- Çift anadal ve yandal işlemleri yapılabiliyor

### Migrasyon

Depo: https://github.com/omu/mokul

- Personel kullanıcıları taşındı
- Personel e-postaları taşındı

### Servisler

Depo:  https://github.com/omu/xokul

TODO: @huseyin

### Sistem

Depo: https://github.com/omu/root ve Depo: https://github.com/omu/nokul

- Kullanıcılar LDAP ile eşzamanlanıyor
- Felaket tatbikatı yapıldı
- TOA etkin
- Uygulama ölçeklendi
- Uygulama staging yayında
- Uygulama production yayında

**Comment by roktas** [comment]
https://github.com/omu/omu/blob/documentation-overhaul/doc/workflow/label.md dokümanına göre tüm etiketleri düzenledim.  Bundan sonra:

- Tartışmaya açmadan yeni etiket eklemeyelim
- Triage yaparken bu etiketleri kullanalım

P.S. Dependabot'tan gelen redundant etiketler var (ruby ve javascript), onları daha sonra halledeceğim.

**Comment by roktas** [comment]
Yeni milestone'ları eklemeden önce mevcut tüm milestone'ları (Sprint'ler) kaldırdım.

**Comment by roktas** [comment]
Bir de gençler, farkettiyseniz bu iş kaydı discuss + urgent olarak etiketlendi.  Niçin kimseden ses yok?

**Comment by ekural** [comment]
Öncelikle sistem üzerinde şuan yapabildiklerimize göz gezdirirsek:

- Sistemde kullanıcı tanımlanabiliyor.
- Birimler tanımlanabiliyor.
- Akademik takvim tanımlanabiliyor.
- Kurul komisyon toplantı bilgileri tutulabiliyor.
- Ders süreçleri tanımlanabiliyor (Müfredat/Dersler/Ders Grupları/Sunulan Dersler)
    - Ders, müfredat değişikliği ile ilgili süreçler eksik. Mükemmel senaryo ile müfredatları tamamen doğru şekilde tanımlanmış ve değişmez olarak düşündük. Değişiklik süreçlerini ikincil iş olarak sonraya bıraktık ancak migrate edeceğimiz datalarda bu tarz veriler olduğu için migrasyon süreçlerinden önce geliştirilmeli.
- Ders kriterleri belirlenebiliyor (Yapılacak değerlendirme türleri ve sayısı)
- Aday öğrenci ve aday personel süreçleri yönetilebiliyor.
- Kullanıcı yetkilendirmeleri yapılabiliyor. (İlgili geliştirme yapıldı. Henüz tam kullanılabilir değil)

Bu senaryoya göre daha önce belirlemiş olduğumuz ilk milestone olan "Öğrenci kayıtlanacağı dersleri görebilmeli" adımına rollerin etkin kullanımı ve ders kayıt ekranlarının oluşturulması kaldı. Bu nedenle bununla ilgili adımları öncelik sırasında korumamız gerekir. 


1. Kullanıcı rolleri etkin
1. Öğrenci kayıtlanabileceği dersleri görebiliyor
(Bu ilk 2 madde tek milestone olarak ele alınıp issue'larla bölünebilir.)
1. Öğrenci ders kaydını gerçekleştirebiliyor.
1. Ders çizelgeleri görüntülenebiliyor. (Taslakta yer alan "Mekanlar G-Suite ile entegre yönetilebiliyor" milestone'un ilk aşamada bize gerekli olan parçası. Neden gerekli? Çünkü ders kayıt aşamasında çakışma kontrollerinin yapılması lazım. Bu kısım bir önceki maddeyle döngüsel ilişkili.)
1. Not giriş ve not görüntüleme işlemleri yapılabiliyor.
(Taslaktaki 8. ve 9. milestoneların birleşimi. Yine altında issue'lar ile ayrılabilir.)
1. Ders değerlendirmeleri yapılabiliyor. (Mutlak, Bağıl değerlendirme süreçleri.) 
1. Mezun öğrenci belirlemesi yapılabiliyor.
1. Diploma işlemleri yapılabiliyor
1. Çift anadal/yandal işlemleri yapılabiliyor.

Diğer milestonelar:
- Müfredat değişiklikleri yönetilebiliyor. (Bu milestone oldukça önemli ve bağlayıcı. Yukarıda yapmış olduğum sıralamada 2-7. milestonelar arasındaki herhangi bir sıraya uyuyor. Öncelik sırası konusunda yorumlarınız bekliyorum.)
- Personel izin talepleri yönetilebiliyor. (Bu milestone'u eklememiz durumunda işin odak noktası personel yönetimi otomasyonuna kayıyor. Buraya kadar personeli öğrenci otomasyonu içerisinde yönetmemizi sağlayacak ölçüde ilgilendik. Eğer bu tarz milestone'lar ekleyeceksek şu anki akışta en sonda yer almalı. Çünkü peşine gelecek/gelmesi gereken pek çok personel issue'su var.)
- Yeni öğrenci kaydı yapılabiliyor, Yeni personel kaydı yapılabiliyor, Personel görevlendirmeleri yönetilebiliyor ( Bu üç milestone yanılmıyorsam Nokul'da yapılabiliyor. O nedenle şimdilik sıralamaya dahil etmedim. Maddelerin kapsamı ile ilgili gözden kaçırdığım birşey varsa ekleyelim)

@omu/product 'tan beklenen işler:
Beklenen işler kısmındaki "due date" belirleme konusunda @omu/backend ile görüşmemiz gerektiğini düşünüyorum. Ancak öncelikle bizim alt issue'ları kısmi de olsa yazmamız gerek. Bize tahmini de olsa her bir iş için adam/saat süresi verirseler ona yaklaşık bir due data belirlemeye çalışırız.

**Comment by abdagli** [comment]
Due date'ler geliştiricilerin proje yöneticileriyle istişare ederek verebilecekleri bir karar bence. Yani po'nun tarih vermesi müşterinin iş için tarih vermesine benzer. PO en fazla şunu demeli; toplam şu 5 milestone Eylül ayına kadar teslim edilmeli gibi.

Dolayısıyla proje yöneticisi ile geliştirici ekip milestone'lar belirlendikten sonra tarihleri girmeliler.

> Bir de gençler, farkettiyseniz bu iş kaydı discuss + urgent olarak etiketlendi. Niçin kimseden ses yok?

Bu etiketlere henüz alisamadim. Daha dikkatli olurum. Gözden kaçırmış in. Benim hatam.

**Comment by abdagli** [comment]
Daha anlaşılır olması için; her bir milestone un due date lerini vermek PO'nun yonetebilecegi birşey olmadığını düşünüyorum. Ancak production konusunda due date talebinde bulunabilir. Zaten bu hepimizin malumu.

**Comment by roktas** [comment]
Due date'lere fazla takıldınız :-)  Bakın orada ne demişim:

> İlk veya ilk bir kaç milestone'a due date koyalım

Tüm milestone'ları kastetmiyorum yani.   İlk milestone için (ortaya çıktıktan sonra) kabaca due date verin diyorum.

**Comment by roktas** [comment]
> Personel izin talepleri yönetilebiliyor. (Bu milestone'u eklememiz durumunda işin odak noktası personel yönetimi otomasyonuna kayıyor. Buraya kadar personeli öğrenci otomasyonu içerisinde yönetmemizi sağlayacak ölçüde ilgilendik. Eğer bu tarz milestone'lar ekleyeceksek şu anki akışta en sonda yer almalı. Çünkü peşine gelecek/gelmesi gereken pek çok personel issue'su var.)

@ekural bunu konuştuk ya.  Nokul tam olarak açılamayacağına göre şu günden itibaren parça parça neyi açabiliriz, bunu hesap edin.  Personel'e falan filana odaklanmayacağız, somut çıktılara odaklanacağız.  Milestone bu demek.

**Comment by abdagli** [comment]
Hocam takilmamizin sebebi due date kere uyamadigimiz zaman ciddi motivasyon problemleri yaşıyoruz. Ayrıca po ve proje yöneticiliği ayrı birer rol. Bir süre sonra karışabiliyor. Bu yüzden biz developer'lar ile görüşüp onların due date vermelerini isteyelim. Haftasonu milestone karı netlestirip bayramdan önce due date leri toplamış oluruz.

**Comment by ekural** [comment]
> @ekural bunu konuştuk ya. Nokul tam olarak açılamayacağına göre şu günden itibaren parça parça neyi açabiliriz, bunu hesap edin. Personel'e falan filana odaklanmayacağız, somut çıktılara odaklanacağız. Milestone bu demek.

Uygulama kısmı yazınca milestone'lar için ben direk öğrenci otomasyonu odaklı yöneldim. Neyi kastettiğinizi şimdi anladım hocam.

**Comment by ekural** [comment]
Roadmap altında bazı başlıkları daha geniş başlıklar altında toplayarak düzenledik. Yeni sıralama ve başlıklara göre kısaca bir tartıştık @omu/product  olarak. Milestoneların github üzerinde girişine ve issueların atanmasına başladık. Hafta içinde son hali olgunlaşacaktır. Analiz ve design issue'larını [po](https://github.com/omu/po) deposunda takip edebilirsiniz. Sonuçlanan issuelar nokul deposunda ilgili milestone altına taşınacaktır.

**Comment by abdagli** [comment]
Toplanti sirasinda bir kac milestone daha eklendi. Tum milestone'lara siralama duzgun olmasi icin rastgele `due date` atandi. Bundan sonra `due date`'ler toplantilar sonucunda belirlenerek proje yoneticisi tarafindan guncellenecektir. Issue'yu kapatiyorum.
