### ISSUE TITLE
Kullanıcı rolleri etkinleştirilmeli

### ISSUE THREAD

**Issue by roktas** [omu/nokul#930]
#### Kullanım senaryosu

Patron ile gelen yetkilendirme alt yapısına dayalı olarak kullanıcı rolleri tüm uygulamada etkinleştirilmeli.

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [X] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [X] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [X] Özellik ürün takımı tarafından incelendi ve onaylandı
- [X] İş kaydını "Product" projesiyle ilişkilendirdim
- [X] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [X] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

**Comment by abdagli** [comment]
Bu issue'yu parcalamamiz lazim. Eger bu bir `feature` issue'su ise, demek oluyorki artık analizi ve tasarımı @omu/product tarafında tamamlanmış ve develop edilmeye hazır. Developer gerekli geliştirmeyi yaptıktan sonra issue kapatılabilir.

Eğer @omu/product tarafından analiz ve tasarım yapılması bekleniyorsa henüz feature ortaya çıkmamıştır. Dolayısıyla issue burada değil, `po` deposunda `analiz` olarak bulunmalıdır. Analiz yapıldıktan sonra issue kapatılarak `design` issue'su açılmalıdır. Tasarım da bittikten sonra buraya `feature` issue'su açılmalıdır.

Bu haliyle bu issue ne zaman kapanır, kimlerin görevi nedir belli değil. Ayrıca `Product` projesinde önceliklendiremeyiz. Analiz mi tasarım mı belli değil.

Eğer geliştirilecek bir şey yoksa (yani Patron artık hazır yönetim panelinden istenilen yetki verilebiliyorsa) Bu artık feature değil ürünün production'a hazır edilmesiyle ilgili veri hazırlık süreci oluyor. `Product` tarafında şuanda böyle bir süreç yok ama artık olmalı.

Ürün süreçleriyle ürünün teslimata hazırlık süreçleri farklı olabilir. Bunun üzerinde çalışacağım. İlgili etiket organizasyonunu yaparım. Ancak o zamana kadar bu issue'yu `po` deposuna almak mantıklı geliyor bana.

**Comment by roktas** [comment]
Bu bir milestone'du (süper epik), ama son aşamasına gelen bir milestone olduğundan issue'ya çevirdim.  Milestone olsaydı bir belirsizlik yoktu, basitçe "Nokul'da rollendirme yapılabiliyor" derdik.  Patron yani rollendirme alt yapısı kabaca tamamlandığından son kısmı kaldı sadece, bunun *etkinleştirilmesi*.  LDAP işinden sonra @isubas bakacak buna, bölme işlemi de o vakit yapılabilir.

**Comment by abdagli** [comment]
O zaman `Product` projesinden kaldırıyorum bunu. `Nokul` projesinde `Patron`'un nihai hale getirilmesi olarak düşünebiliriz bunu. Dolayısıyla bir @omu/backend'in teslim etmesini beklediğimiz bir issue. Sonrasında @omu/product ürün teslim sürecine dahil edecektir. Henüz o aşamada değiliz sanırım.

**Comment by msdundar** [comment]
Buradan epey bir story cikmasi lazim, user-facing ve deliverable olan herseyi story haline getirelim. Hemen her controller'a rol eklenecegi icin her biri ayri story olarak bu epic altinda olabilir.

**Comment by roktas** [comment]
> Bu issue'yu parcalamamiz lazim. Eger bu bir feature issue'su ise, demek oluyorki artık analizi ve tasarımı @omu/product tarafında tamamlanmış ve develop edilmeye hazır. Developer gerekli geliştirmeyi yaptıktan sonra issue kapatılabilir.

@abdagli: "feature"ın eski "feature-step" olduğuna mutabıkız.  İş kayıtlarını hızlıca yeni düzene geçirirken ben "feature" olarak etiketledim (epic olması lazımdı), Product ilişkilendirmesini de o nedenle yaptım, buna bir bakın anlamında.  (Hatırlarsan @ekural ve sana da söyledim, yeni yapıya göre tüm iş kayıtlarına bir bakalım diye).  Etiketlere "feature" demek ki product tarafı bitti gibi bir kanaate varmayın, çok çok etiket hatalıdır değiştiririz.  @isubas ile bir araya gelerek @msdundar'ın dediği gibi bölme yapmak lazım.

**Comment by abdagli** [comment]
> Bu issue'yu parcalamamiz lazim. 

Ben de issue'yu inceledim ve parcalanmasi gerektigini belirtmistim zaten hocam.

**Comment by roktas** [comment]
Bu tür durumlarda ne yapacağımaz karar vermemiz lazım.  Böyle epic bir iş kaydı geldi diyelim (epic etiketli).  Product ön çalışması gerekiyor ise iş kaydını Product panosuyla ilişkilendirelim diyorum.  Örneğin bu iş kaydında @isubas'ı yönlendirme anlamında birlikte çalışmanız lazım.

**Comment by abdagli** [comment]
Bence is kayitlarinin bir tane sorumlusu olmali. Birlikte calisilacaksa dahi bir sorumlu olmali. Eger analizi, tasarimi yapilacaksa isin, bu is kaydi `po` deposunda olmali. Orada once dokumante edilmeli. Sonra buraya is acilmali. Ancak bu is zaten bir hayli olgunlasti. Artik urun tesliminde kullanilacak roller belirlenecek. Yani eger rollendirme hazirsa, nereye ne rol eklenecegi ayri bir isin konusu ve bu `po` deposu ve `Product` projesinin konusu. Sonra bu da belirlenince gelistirici ekip ilgili duzenlemeleri yapar.

Yani suanda rollendirme yapabiliyor muyuz? Bu sorunun cevabi evet ise bu issue tamamdir. Bu benim gorusum.

**Comment by roktas** [comment]
> Yani eger rollendirme hazirsa, nereye ne rol eklenecegi ayri bir isin konusu ve bu po deposu ve Product projesinin konusu.

Ben anlatamadım kendimi. :-)

TLDR; Rollendirme konusunda daha başından itibaren milestone tabanlı yeni çalışma düzeninde çalışsaydık bunları belki konuşmuyor olacaktık.  Herşeyi bir milestone'da toplayacaktık: "Kullanıcılar rollendirilebiliyor".    Ama bunu yapmadığımızdan kalan işe göre kırpılmış bir milestone ile ("Kullanıcı rolleri etkin") başladım sonra da bunu Product ekibiyle geliştiricilerin birlikte karar vermesi/bölmesi gereken bir epic issue'ya dönüştürdüm.  Lakin bu dönüştürmede hatalı etiketleme yaptım.

Tam hikaye şöyle:

- @isubas Patron'u (eski üsül çalışarak) bitirdi ama "entegre" etmedi/henüz edemedi.

- Ramazan ayının ikinci yarısında işi gücü bırakıp "Daha verimli nasıl çalışalım?  Roadmap lazım, bu nasıl olsun?" soruları üzerinde çalışmaya başladım.

- Sonunda ulaştığım noktada Roadmap'lerin (pratik ve işlevsel olması için) milestone'larla kurulmasına karar verdim ve süreci dokümante ettim (hatta çalışmayı daha genişleterek tüm dokümantasyona, şablonlara, etiketlere) el attım.

- Dokümante ettiğim sistematiğe göre (size de haber vererek), Nokul'daki iş kayıtlarına döndüm ve önden milestone'lar çıkardım.  Bu iş kaydı da aslında bir milestone idi.  Yani bölünmesi lazımdı (çünkü milestone = super epic), yani bir feature değildi.

- Sonra toplantı yaptık ve milestone'lar vs biraz daha gelişti.  İş kayıtlarının tümüne de bakalım dedim.  

- (Arada belirtmediğim husus) Ecmel'in #929 üzerinde çalışırken iş kaydını [Personel profilleri yönetilebiliyor](https://github.com/omu/nokul/milestone/5) milestone'a bağlaması gerekirken "Kullanıcı rolleri etkin" milestone'una bağladığını farkettim.  Ona haber vererek bunu düzeltmek yerine, root cause'a baktım (yakın vadeli iki paralel milestone) "Hmm, bu karışıklığa yol açmasın, en iyisi bunu milestone değil Product panosuyla ilişkili epic issue yapayım" dedim.  Ama bunu yaparken etiketlemede hata yaptım, "epic" etiketi koymadım, "feature" etiketi koydum.

> Artik urun tesliminde kullanilacak roller belirlenecek. Yani eger rollendirme hazirsa, nereye ne rol eklenecegi ayri bir isin konusu ve bu po deposu ve Product projesinin konusu. Sonra bu da belirlenince gelistirici ekip ilgili duzenlemeleri yapar.

Bu anlattıklarıma göre cenazeyi nasıl kaldıralım hep birlikte siz karar verin.

**Comment by abdagli** [comment]
> Bu anlattıklarıma göre cenazeyi nasıl kaldıralım hep birlikte siz karar verin.

Ben de yukarida onerimi sunmaya calistim. Eger Patron hazirsa, yani kullanilabilir haldeyse, sadece hangi controller'da hangi yetkiler olacak buna karar verecegimiz yerdeysek, `Product` projesinde ilk ongorulen rolleri cikartalim ve sonra buraya gelerek bu rolleri bir gorelim diyelim.

Product ekibinin kendi reposu var. Buraya epic acip orada alt issue'lari nasil ilerletecegiz. Ayni sekilde product ekibinin kendi etiketleri var. Bu ikisini bir araya getiremedigim icin bu issue tamamsa kapatalim dedim. Yani `epic` gibi davranamadim.

**Comment by roktas** [comment]
> Product ekibinin kendi reposu var. Buraya epic acip orada alt issue'lari nasil ilerletecegiz. Ayni sekilde product ekibinin kendi etiketleri var. Bu ikisini bir araya getiremedigim icin bu issue tamamsa kapatalim dedim. Yani epic gibi davranamadim.

Toplantıda bunu anlattım ya?  Product panosu bunun için var.  Toplantıda bahsettiğim temel mantık/iş akışı şuydu:

- Her projede falanca takımın (sistem yöneticileri, ürün yöneticileri) aktif müdahalesini gerektiren "issue"ları o takımı arkalayan depoda (sistem yöneticileri için omu/root, ürün yöneticileri için omu/po) açmak **yerine**, hemen kendi yerinde/deposunda açalım ve o takımın panosuyla ilişkilendirelim.

- Pek çok durumda ilgili takım panosuna düşen iş kaydını triage ettikten sonra, kayıt üzerinde originate eden depodan çıkarmadan çalışabilir.  Ama ilgili takım, çeşitli nedenlerle iş kaydını kendi depolarına *transfer* edebilir.  Bu iş kaydında yapmak istediğiniz buysa sorun yok, omu/po'ya transfer edebilirsiniz.

**Comment by isubas** [comment]
Close with #1517
