### ISSUE TITLE
Personel sayfaları düzenlenmeli

### ISSUE THREAD

**Issue by ekural** [omu/nokul#941]
Personel sayfalarında görüntülenecek bilgiler belirlenmesi ve buna uygun geliştirme süreçleri yürütülmesi ile ilgili süreçler.

[//]: # (Kullanım senaryosunu yaz veya dış bir dokümana bağlantı oluştur)

#### Katkı sağlama

[//]: # (Bu iş kaydının sana atanmasını istiyor musun?)
[//]: # (Yardımına/bilgisine ihtiyaç duyduğun diğer ekip üyeleri varsa burada nasıl bir yardıma ihtiyaç duyduğunu belirt.)

- [ ] Evet, bu iş kaydının bana atanmasını istiyorum.

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Özellik ürün takımı tarafından incelendi ve onaylandı
- [x] İş kaydını "Product" projesiyle ilişkilendirdim
- [x] İş kaydıyla ilgili uygun etiketlemeleri yaptım
- [ ] Bu iş kaydıyla alakalı açık olarak bekleyen bir [issue](../issues) yok
- [x] Bu iş kaydıyla alakalı açık olarak bekleyen bir [pull request](../pulls) yok

#### Ek içerik

[//]: # (Kullanım senaryosuna ilave açıklamalar)
[//]: # (Mockuplar)
[//]: # (Kaynaklar)
[//]: # (Dış bağlantılar)
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)

**Comment by roktas** [comment]
Bu epik iş kaydı şu anki haliyle yararsız.  Amaç parçalama yapmadan önce kayıt düşmekse zaten (süper epik) bir milestone'umuz var (https://github.com/omu/nokul/milestone/5), kayıt işlevini o görüyor.  Amaç parçalamaksa zaten ilgili milestone altında parçalar çıkmaya başladı.  Enerjimizi parçalamaya yoğunlaştıralım.  Yine de kaydı şimdilik kapatmıyorum, bu kararı iş kaydını açana bırakayım, belki farklı bir amaçla açılmıştır.

**Comment by ekural** [comment]
Bu konuyu epik haline getirme sebebim her ne kadar milestone'un adı personel bilgileri yönetilebiliyor olsa da içerisinde rol yönetimi, kullanıcı tercihleri yönetimi gibi yapılmakta olan veya yapılacak diğer epikleri barındırmasıydı. Ayırma yoluna gittiğim için kendine ait iş parçalarını oluşturması amacıda var tabiki. Yani özetle milestonela genel, uzun soluklu iş parçası hedeflediğimizden konuyu ayrık alt hikayeler halinde düşündüğüm için açtım. Bu tarz amaçlar için epikle hikayeyi tümleştirme yoluna gitmeyelim diyorsanız kapatalım hocam.

**Comment by roktas** [comment]
> Yani özetle milestonela genel, uzun soluklu iş parçası hedeflediğimizden konuyu ayrık alt hikayeler halinde düşündüğüm için açtım.

Epik olmasına itirazım yok, epikliğin boyutuna itirazım var. :-)  Milestone'a çok yakın olmuş, temel sorun bu.  Karşılaştıralım: "Personel bilgileri yönetilebiliyor" vs "Personel sayfaları düzenlenmeli".  Epik olacaksa milestone'a göre (moda tabirle) 3-5 tık daha az epik olmalı en azından.  Ama mümkünse doğrudan küçük (epik olmayan) parçalar da girilebilir.
